import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const poppins = Poppins({
   subsets: ["latin"],
   display: "swap",
   variable: "--poppins-font",
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
   style: ["normal"],
 });

export const metadata: Metadata = {
   title: "Shopping Website",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${poppins.variable} font-sans`}>
         <body>
            <Header />
            {children}
         </body>
      </html>
   );
}
